# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 150, 221, 221))
        self.pushButton.setStyleSheet("border-radius:0px")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/plutao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setShortcut("")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/espaço.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 90, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 100, 171, 41))
        font = QtGui.QFont()
        font.setFamily("poppins")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 255, 0);\n"
"font-family: \'poppins\';\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton_mercurio = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mercurio.setGeometry(QtCore.QRect(560, 140, 171, 28))
        self.pushButton_mercurio.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_mercurio.setObjectName("pushButton_mercurio")
        self.pushButton_venus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_venus.setGeometry(QtCore.QRect(560, 170, 171, 28))
        self.pushButton_venus.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_venus.setObjectName("pushButton_venus")
        self.pushButton_netuno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_netuno.setGeometry(QtCore.QRect(560, 260, 171, 28))
        self.pushButton_netuno.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_netuno.setObjectName("pushButton_netuno")
        self.pushButton_urano = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_urano.setGeometry(QtCore.QRect(560, 290, 171, 28))
        self.pushButton_urano.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_urano.setObjectName("pushButton_urano")
        self.pushButton_terra = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_terra.setGeometry(QtCore.QRect(560, 230, 171, 28))
        self.pushButton_terra.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_terra.setObjectName("pushButton_terra")
        self.pushButton_mars = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mars.setGeometry(QtCore.QRect(560, 200, 171, 28))
        self.pushButton_mars.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_mars.setObjectName("pushButton_mars")
        self.pushButton_saturno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saturno.setGeometry(QtCore.QRect(560, 320, 171, 28))
        self.pushButton_saturno.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_saturno.setObjectName("pushButton_saturno")
        self.pushButton_jupiter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jupiter.setGeometry(QtCore.QRect(560, 350, 171, 28))
        self.pushButton_jupiter.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_jupiter.setObjectName("pushButton_jupiter")
        self.pushButton_bigbang = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bigbang.setGeometry(QtCore.QRect(560, 380, 171, 28))
        self.pushButton_bigbang.setStyleSheet("background-color:\'transparent\';\n"
"border: 2px solid rgb(135, 29, 2);\n"
"font-family: \'poppins\' ;\n"
"color:rgb(0, 255, 0);")
        self.pushButton_bigbang.setObjectName("pushButton_bigbang")
        self.label.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_mercurio.raise_()
        self.pushButton_venus.raise_()
        self.pushButton_netuno.raise_()
        self.pushButton_urano.raise_()
        self.pushButton_terra.raise_()
        self.pushButton_mars.raise_()
        self.pushButton_saturno.raise_()
        self.pushButton_jupiter.raise_()
        self.pushButton_bigbang.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Pontos: 0"))
        self.label_3.setText(_translate("MainWindow", "Loja de Upgrades:"))
        self.pushButton_mercurio.setText(_translate("MainWindow", "Mercurio: 100pts"))
        self.pushButton_venus.setText(_translate("MainWindow", "Venus: 500pts"))
        self.pushButton_netuno.setText(_translate("MainWindow", "Netuno: 1200pts"))
        self.pushButton_urano.setText(_translate("MainWindow", "Urano: 1500pts"))
        self.pushButton_terra.setText(_translate("MainWindow", "Terra: 1100pts"))
        self.pushButton_mars.setText(_translate("MainWindow", "Marte: 1000pts"))
        self.pushButton_saturno.setText(_translate("MainWindow", "Saturno: 2000pts"))
        self.pushButton_jupiter.setText(_translate("MainWindow", "Jupiter: 2500pts"))
        self.pushButton_bigbang.setText(_translate("MainWindow", "BIG BANG: 3000pts"))
